### DISCUSSION TITLE
Error occurred while processing GET request while using pyspark

### DISCUSSION THREAD

**Discussion by lalitbyteiq** [apache/amoro#3325] [Q&A]
Hi im getting the bellow error while trying to connect amoro using pyspark jupyter 
here are my details 

docker compose :

```
version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      amoro_network:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      amoro_network:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
  amoro:
    image: apache/amoro
    container_name: amoro
    ports:
      - 8081:8081
      - 1630:1630
      - 1260:1260
    environment:
      - JVM_XMS=1024
    networks:
      amoro_network:
        aliases:
          - warehouse.minio
    volumes:
      - ./amoro:/tmp/warehouse
    command: ["/entrypoint.sh", "ams"]
    tty: true
    stdin_open: true

  spark-iceberg:
    image: tabulario/spark-iceberg:3.3.2_1.3.0
    container_name: spark-iceberg
    build: spark/
    networks:
      amoro_network:
    depends_on:
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
      - ./jars/amoro-mixed-format-spark-runtime-3.3-0.7.0-incubating.jar:/opt/spark/jars/amoro-mixed-format-spark-runtime-3.3-0.7.0-incubating.jar
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - SPARK_OPTS=--packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.3.0,org.apache.amoro:amoro-mixed-spark-3.3-runtime:0.7.0

    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001

networks:
  amoro_network:
    driver: bridge
```

    here is my pyspark code
    
    from pyspark.sql import SparkSession

AMS_HOST = "amoro"  
AMS_PORT = "1260"
AMS_CATALOG_NAME = "demo_catalog"

spark = SparkSession.builder \
    .appName("MySparkApp") \
    .config("spark.jars.packages", "org.apache.amoro:amoro-mixed-spark-3.3-runtime:0.7.0") \
    .config("spark.sql.extensions", "org.apache.amoro.spark.MixedFormatSparkExtensions") \
    .config("spark.sql.catalog.local_catalog", "org.apache.amoro.spark.MixedFormatSparkCatalog") \
    .config("spark.sql.catalog.local_catalog.url", f"thrift://{AMS_HOST}:{AMS_PORT}/{AMS_CATALOG_NAME}") \
    .getOrCreate()

# Set the catalog
spark.sql("use local_catalog")

error

Py4JJavaError: An error occurred while calling o36.sql.
: org.apache.iceberg.exceptions.RESTException: Error occurred while processing GET request
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:304)
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:219)
	at org.apache.iceberg.rest.HTTPClient.get(HTTPClient.java:320)
	at org.apache.iceberg.rest.RESTSessionCatalog.fetchConfig(RESTSessionCatalog.java:823)
	at org.apache.iceberg.rest.RESTSessionCatalog.initialize(RESTSessionCatalog.java:167)
	at org.apache.iceberg.rest.RESTCatalog.initialize(RESTCatalog.java:68)
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:239)
	at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:284)
	at org.apache.iceberg.spark.SparkCatalog.buildIcebergCatalog(SparkCatalog.java:144)
	at org.apache.iceberg.spark.SparkCatalog.initialize(SparkCatalog.java:552)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:60)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$catalog$1(CatalogManager.scala:53)
